import { Train, JobCard } from './types';

export const mockTrains: Train[] = [
  {
    id: '1',
    trainId: 'TR-001',
    status: 'Run',
    mileage: 45000,
    brandingHours: 120,
    fitnessStatus: 'Excellent',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Regular service route',
  },
  {
    id: '2',
    trainId: 'TR-002',
    status: 'Run',
    mileage: 38000,
    brandingHours: 95,
    fitnessStatus: 'Good',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Peak hour operations',
  },
  {
    id: '3',
    trainId: 'TR-003',
    status: 'Run',
    mileage: 52000,
    brandingHours: 140,
    fitnessStatus: 'Good',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Express line service',
  },
  {
    id: '4',
    trainId: 'TR-004',
    status: 'Run',
    mileage: 41000,
    brandingHours: 110,
    fitnessStatus: 'Excellent',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Normal operations',
  },
  {
    id: '5',
    trainId: 'TR-005',
    status: 'Standby',
    mileage: 35000,
    brandingHours: 85,
    fitnessStatus: 'Good',
    cleaningStatus: 'Needs Cleaning',
    brandingStatus: 'In Progress',
    reasonNotes: 'Scheduled for cleaning',
  },
  {
    id: '6',
    trainId: 'TR-006',
    status: 'Standby',
    mileage: 48000,
    brandingHours: 130,
    fitnessStatus: 'Good',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Reserve unit',
  },
  {
    id: '7',
    trainId: 'TR-007',
    status: 'Standby',
    mileage: 29000,
    brandingHours: 70,
    fitnessStatus: 'Excellent',
    cleaningStatus: 'Clean',
    brandingStatus: 'Pending',
    reasonNotes: 'Awaiting branding update',
  },
  {
    id: '8',
    trainId: 'TR-008',
    status: 'Maintenance',
    mileage: 67000,
    brandingHours: 180,
    fitnessStatus: 'Requires Inspection',
    cleaningStatus: 'Dirty',
    brandingStatus: 'Complete',
    reasonNotes: 'Scheduled maintenance check',
  },
  {
    id: '9',
    trainId: 'TR-009',
    status: 'Maintenance',
    mileage: 71000,
    brandingHours: 200,
    fitnessStatus: 'Poor',
    cleaningStatus: 'Needs Cleaning',
    brandingStatus: 'In Progress',
    reasonNotes: 'Engine overhaul required',
  },
  {
    id: '10',
    trainId: 'TR-010',
    status: 'Maintenance',
    mileage: 55000,
    brandingHours: 150,
    fitnessStatus: 'Requires Inspection',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Brake system check',
  },
  {
    id: '11',
    trainId: 'TR-011',
    status: 'Run',
    mileage: 43000,
    brandingHours: 115,
    fitnessStatus: 'Good',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Night shift operations',
  },
  {
    id: '12',
    trainId: 'TR-012',
    status: 'Standby',
    mileage: 31000,
    brandingHours: 80,
    fitnessStatus: 'Excellent',
    cleaningStatus: 'Clean',
    brandingStatus: 'Complete',
    reasonNotes: 'Ready for deployment',
  },
];

export const mockJobCards: JobCard[] = [
  {
    id: '1',
    jobCardId: 'JC-001',
    trainId: 'TR-008',
    taskType: 'Maintenance',
    priority: 'High',
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'In Progress',
    description: 'Complete brake system inspection and replacement',
  },
  {
    id: '2',
    jobCardId: 'JC-002',
    trainId: 'TR-009',
    taskType: 'Maintenance',
    priority: 'High',
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'In Progress',
    description: 'Engine overhaul and performance testing',
  },
  {
    id: '3',
    jobCardId: 'JC-003',
    trainId: 'TR-005',
    taskType: 'Cleaning',
    priority: 'Medium',
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'Pending',
    description: 'Deep interior and exterior cleaning',
  },
  {
    id: '4',
    jobCardId: 'JC-004',
    trainId: 'TR-007',
    taskType: 'Branding',
    priority: 'Medium',
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'Pending',
    description: 'Apply new promotional branding for festival season',
  },
  {
    id: '5',
    jobCardId: 'JC-005',
    trainId: 'TR-010',
    taskType: 'Maintenance',
    priority: 'High',
    deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'In Progress',
    description: 'Safety systems calibration and testing',
  },
  {
    id: '6',
    jobCardId: 'JC-006',
    trainId: 'TR-003',
    taskType: 'Maintenance',
    priority: 'Low',
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: 'Pending',
    description: 'Routine 50k km service check',
  },
];
